#!/bin/sh

# symlink .git/hooks/pre-commit to this for checking of gofmt and jsfmt

fail=""

#jsfiles=$(git diff --cached --name-only --diff-filter=ACM | grep '^js/pkunk/\.js$')
#if [ -n "$jsfiles" ]
#then
#	jsfail=$(jsfmt -l $jsfiles)
#	if [ -n "$jsfail" ]
#	then
#		fail="yeah"
#		echo >&2 "JS files must be formatted with jsfmt.  Please run:"
#		for js in $jsfail; do
#			echo >&2 "   jsfmt -w $PWD/$js"
#		done
#		echo >&2
#	fi
#fi

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')
if [ -n "$gofiles" ]
then
	gofail=$(gofmt -l $gofiles)
	if [ -n "$gofail" ]
	then
		fail="yeah"
		echo >&2 "Go files must be formatted with gofmt. Please run:"
		for go in $gofail; do
			echo >&2 "   gofmt -w $PWD/$go"
		done
		echo >&2
	fi
fi

[ -z "$fail" ] && exit 0

echo >&2 "Or, to format everything, you can run:"
echo >&2 "   make fmt"
echo >&2

exit 1
